pull_request_rules:
  - name: Automatic merge for Renovate
    conditions:
      - author=renovate[bot]
      - check-success=Eldoria CI / build-and-test
    actions:
      merge:
        method: squash