# Consolidated test file
# Auto-generated by Regression Hunter
import sys
import os
from unittest.mock import MagicMock

# Ensure the project root is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

# Pre-patch dependencies to allow top-level imports during collection
if "pymongo" not in sys.modules:
    sys.modules["pymongo"] = MagicMock()
if "pymongo.errors" not in sys.modules:
    sys.modules["pymongo.errors"] = MagicMock()
if "discord" not in sys.modules:
    sys.modules["discord"] = MagicMock()


# Now import modules under test
from database.database_manager import DatabaseManager  # noqa: E402

from database.database_manager import DatabaseManager  # noqa: E402
from game_systems.guild_system.guild_exchange import GuildExchange  # noqa: E402
from game_systems.player.player_creator import PlayerCreator  # noqa: E402
from unittest.mock import AsyncMock, MagicMock, Mock, patch
from unittest.mock import MagicMock
from unittest.mock import MagicMock, patch

import asyncio
import importlib

import os
import sys
import unittest


# ------------------------------------------------------------
# Merged from test_security.py
# ------------------------------------------------------------
"""
Security Test Suite
-------------------
Verifies that player names are sanitized against Markdown injection and excessive length.
SAFE: Uses mocked DatabaseManager.
"""

# Add root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock external dependencies for environments where they aren't installed
_original_discord = sys.modules.get("discord")
_original_discord_ext = sys.modules.get("discord.ext")
_mocked_discord = False

try:
    import pymongo  # noqa: F401
except ImportError:
    sys.modules["pymongo"] = MagicMock()
    sys.modules["pymongo.errors"] = MagicMock()

try:
    import discord  # noqa: F401
    import discord.ext  # noqa: F401
except ImportError:
    sys.modules["discord"] = MagicMock()
    sys.modules["discord.ext"] = MagicMock()
    _mocked_discord = True

# Restore original discord modules to prevent polluting other tests
if _mocked_discord:
    if _original_discord is not None:
        sys.modules["discord"] = _original_discord
    else:
        sys.modules.pop("discord", None)
    if _original_discord_ext is not None:
        sys.modules["discord.ext"] = _original_discord_ext
    else:
        sys.modules.pop("discord.ext", None)


class TestSecurity(unittest.TestCase):
    def setUp(self):
        # Mock DatabaseManager
        self.mock_db = MagicMock(spec=DatabaseManager)
        self.creator = PlayerCreator(self.mock_db)

    def test_markdown_sanitization(self):
        """Test that markdown characters are removed from username."""
        discord_id = 12345
        dirty_name = "**Bold**_Italic_`Code`"
        expected_clean_name = "BoldItalicCode"

        # Mock player not existing
        self.mock_db.player_exists.return_value = False
        self.mock_db.get_default_skill_keys.return_value = []

        success, msg = self.creator.create_player(discord_id, dirty_name, 1)  # 1 is a valid class_id

        self.assertTrue(success, f"Player creation failed: {msg}")

        # Verify create_player_full called with sanitized name
        self.mock_db.create_player_full.assert_called()
        args, kwargs = self.mock_db.create_player_full.call_args
        # username is 2nd positional arg or keyword 'username'
        actual_name = kwargs.get("username", args[1] if len(args) > 1 else None)

        self.assertEqual(actual_name, expected_clean_name, "Markdown characters were not removed!")

    def test_link_sanitization(self):
        """Test that link markdown characters are removed from username."""
        discord_id = 12345
        dirty_name = "[Click Me](http://evil.com)"

        # Expected: brackets and parentheses removed
        expected_clean_name = "Click Mehttp://evil.com"

        self.mock_db.player_exists.return_value = False
        self.mock_db.get_default_skill_keys.return_value = []

        success, msg = self.creator.create_player(discord_id, dirty_name, 1)

        self.assertTrue(success, f"Player creation failed: {msg}")

        self.mock_db.create_player_full.assert_called()
        args, kwargs = self.mock_db.create_player_full.call_args
        actual_name = kwargs.get("username", args[1] if len(args) > 1 else None)

        # Assert no brackets or parens
        self.assertNotIn("[", actual_name)
        self.assertNotIn("]", actual_name)
        self.assertNotIn("(", actual_name)
        self.assertNotIn(")", actual_name)

        # Also check exact match to confirm behavior
        self.assertEqual(actual_name, expected_clean_name)

    def test_zalgo_and_length(self):
        """Test that name is truncated to 32 chars."""
        discord_id = 67890
        long_name = "A" * 50
        expected_len = 32

        self.mock_db.player_exists.return_value = False
        self.mock_db.get_default_skill_keys.return_value = []

        success, msg = self.creator.create_player(discord_id, long_name, 1)

        self.assertTrue(success, f"Player creation failed: {msg}")

        self.mock_db.create_player_full.assert_called()
        args, kwargs = self.mock_db.create_player_full.call_args
        actual_name = kwargs.get("username", args[1] if len(args) > 1 else None)

        self.assertEqual(len(actual_name), expected_len, "Name was not truncated!")
        self.assertEqual(actual_name, "A" * 32)


def run_all_tests():
    """Run the security test suite manually."""
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromTestCase(TestSecurity)
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    return result.wasSuccessful()


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_security_developer.py
# ------------------------------------------------------------
"""
Security tests for developer_cog.py — verifies owner-only access to dev_panel.

Handles test pollution: other test files mock ``discord`` at module level
during pytest collection.  This module patches the critical parts of the
mocked discord (Cog base class, app_commands.command decorator, ui classes)
to be real objects, then reimports ``cogs.developer_cog`` in a clean state.
"""

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ── Minimal stand-in classes ────────────────────────────────────────────

class _Cog:
    """Minimal stand-in for discord.ext.commands.Cog."""
    def __init__(self, bot=None, *args, **kwargs):
        self.bot = bot

class _View:
    """Minimal stand-in for discord.ui.View."""
    def __init__(self, timeout=None):
        self.children = []
    def add_item(self, item):
        self.children.append(item)
    def clear_items(self):
        self.children.clear()

class _Button:
    """Minimal stand-in for discord.ui.Button."""
    def __init__(self, label=None, style=None, emoji=None, row=None, custom_id=None, disabled=False):
        self.label = label
        self.style = style
        self.disabled = disabled
        self.callback = None
    def _is_v2(self):
        return False

# ── Helper to load cog with patched dependencies ───────────────────────

def _load_developer_cog():
    """Load DeveloperCog with mocked dependencies in a clean environment."""

    # Create fresh mocks for discord and pymongo
    mock_discord = MagicMock()
    mock_discord.ext.commands.Cog = _Cog
    mock_discord.ui.View = _View
    mock_discord.ui.Button = _Button

    # Mock app_commands.command decorator
    def command_decorator(*args, **kwargs):
        def decorator(func):
            # Attach the callback directly to the function wrapper
            func.callback = func
            # Mock the .error decorator
            func.error = lambda f: f
            return func
        return decorator

    mock_discord.app_commands.command = command_decorator

    # Create module dictionary to patch
    modules_to_patch = {
        "discord": mock_discord,
        "discord.ext": mock_discord.ext,
        "discord.ext.commands": mock_discord.ext.commands,
        "discord.app_commands": mock_discord.app_commands,
        "discord.ui": mock_discord.ui,
        "pymongo": MagicMock(),
        "pymongo.errors": MagicMock(),
        "database.database_manager": MagicMock(),  # Mock DB manager
    }

    # Apply patches and import the cog
    with patch.dict(sys.modules, modules_to_patch):
        # Force reload to pick up the patched modules
        if "cogs.developer_cog" in sys.modules:
            del sys.modules["cogs.developer_cog"]

        import cogs.developer_cog
        importlib.reload(cogs.developer_cog)
        return cogs.developer_cog.DeveloperCog

# ── Tests ───────────────────────────────────────────────────────────────

class TestSecurityDeveloper(unittest.IsolatedAsyncioTestCase):

    async def test_dev_panel_access_denied_for_non_owner(self):
        """Verify that dev_panel denies access to non-owners."""
        DeveloperCog = _load_developer_cog()

        bot = MagicMock()
        bot.is_owner = AsyncMock(return_value=False)

        cog = DeveloperCog(bot)

        # Mock DB interaction in the cog
        cog.db = MagicMock()

        interaction = MagicMock()
        interaction.user = MagicMock()
        interaction.response = MagicMock()
        interaction.response.send_message = AsyncMock()
        interaction.response.defer = AsyncMock()

        # Execute the command callback
        # Since we mocked the decorator to return the function, cog.dev_panel is the bound method.
        await cog.dev_panel(interaction)

        bot.is_owner.assert_awaited_once_with(interaction.user)
        interaction.response.send_message.assert_awaited_with("⛔ You are not the bot owner.", ephemeral=True)
        interaction.response.defer.assert_not_awaited()

    async def test_dev_panel_access_granted_for_owner(self):
        """Verify that dev_panel grants access to owners."""
        DeveloperCog = _load_developer_cog()

        bot = MagicMock()
        bot.is_owner = AsyncMock(return_value=True)

        cog = DeveloperCog(bot)

        # Mock DB data
        cog.db = MagicMock()
        cog.db.get_player.return_value = {
            "name": "Owner",
            "experience": 0,
            "aurum": 0,
            "vestige_pool": 0,
        }
        cog.db.get_active_boosts.return_value = []

        interaction = MagicMock()
        interaction.user = MagicMock()
        interaction.response = MagicMock()
        interaction.response.defer = AsyncMock()
        interaction.followup = MagicMock()
        interaction.followup.send = AsyncMock()

        await cog.dev_panel(interaction)

        bot.is_owner.assert_awaited_once_with(interaction.user)
        interaction.response.defer.assert_awaited_with(ephemeral=True)

if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_security_exchange.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock pymongo completely
mock_pymongo = MagicMock()
mock_pymongo_errors = MagicMock()
mock_pymongo.errors = mock_pymongo_errors
sys.modules["pymongo"] = mock_pymongo
sys.modules["pymongo.errors"] = mock_pymongo_errors


class TestGuildExchangeSecurity(unittest.TestCase):
    def setUp(self):
        # We need to re-instantiate because DatabaseManager is a singleton
        DatabaseManager._instance = None

        self.mock_db = MagicMock(spec=DatabaseManager)
        # Mock the _col method to return a mock collection
        self.mock_collection = MagicMock()
        self.mock_db._col.return_value = self.mock_collection
        self.mock_db.db = MagicMock()  # Mock the db attribute
        self.mock_db.db.__getitem__.return_value = self.mock_collection  # Mock db['collection']

        # Patch DatabaseManager to avoid actual init
        with patch("database.database_manager.MongoClient"):
            self.exchange = GuildExchange(self.mock_db)

    def test_exchange_all_materials_race_condition_fix(self):
        """
        Test that exchange_all_materials uses atomic find_one_and_delete
        instead of calculate-then-delete_many to prevent race conditions.
        """
        discord_id = 12345

        # Setup mock items
        item1 = {"id": 1, "item_key": "iron_ore", "count": 5, "item_type": "material"}
        item2 = {"id": 2, "item_key": "gold_ore", "count": 2, "item_type": "material"}

        # Mock find to return items (initial scan)
        self.mock_collection.find.return_value = [item1, item2]

        # Mock find_one_and_delete to return the item (successful delete)
        # We simulate that item1 is successfully deleted, but item2 was already deleted by another process (returns None)
        self.mock_collection.find_one_and_delete.side_effect = [item1, None]

        # Mock increment_player_fields
        self.mock_db.increment_player_fields = MagicMock()

        # Mock MATERIALS data
        with patch(
            "game_systems.guild_system.guild_exchange.MATERIALS", {"iron_ore": {"value": 10}, "gold_ore": {"value": 50}}
        ):
            # Set db on exchange object (it's set in init but let's be sure)
            self.exchange.db = self.mock_db

            total_value, items = self.exchange.exchange_all_materials(discord_id)

            # Verify results
            # Only item1 should contribute to value: 5 * 10 = 50
            # item2 (2 * 50 = 100) should NOT contribute because find_one_and_delete returned None
            self.assertEqual(
                total_value, 50, f"Expected 50 but got {total_value}. This confirms race condition fix is needed."
            )
            self.assertEqual(len(items), 1)
            self.assertEqual(items[0]["id"], 1)

            # Verify DB calls
            # 1. find called to get IDs
            self.mock_collection.find.assert_called_with({"discord_id": discord_id, "item_type": "material"})

            # 2. find_one_and_delete called for each item
            self.mock_collection.find_one_and_delete.assert_any_call({"id": 1, "discord_id": discord_id})
            self.mock_collection.find_one_and_delete.assert_any_call({"id": 2, "discord_id": discord_id})

            # 3. increment_player_fields called with correct amount
            self.mock_db.increment_player_fields.assert_called_with(discord_id, aurum=50)


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_security_shop.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock discord before importing anything that uses it
mock_discord = MagicMock()

# Ensure View is a class that can be inherited from without creating a MagicMock for every method
class MockView:
    def __init__(self, *args, **kwargs):
        self.children = []

    def add_item(self, item):
        self.children.append(item)
        return self # add_item typically returns self or None, strictly View.add_item returns self in some versions or None in others. discord.py returns None usually.

    def clear_items(self):
        self.children.clear()

    def stop(self):
        pass

    # Allow async context manager if needed
    async def __aenter__(self): return self
    async def __aexit__(self, exc_type, exc, tb): pass

mock_discord.ui.View = MockView

sys.modules["discord"] = mock_discord
sys.modules["discord.ui"] = mock_discord.ui
sys.modules["discord.ext"] = MagicMock()
sys.modules["discord.ext.commands"] = MagicMock()
sys.modules["discord.app_commands"] = MagicMock()
sys.modules["pymongo"] = MagicMock()
sys.modules["pymongo.errors"] = MagicMock()

# Import normally (it will use the mock)
try:
    # ruff: noqa: F401
    import cogs.shop_cog
    from cogs.shop_cog import ShopView
except ImportError:
    ShopView = None


class TestSecurityShop(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        # Force reload cogs.shop_cog to ensure ShopView uses our mocks
        if "cogs.shop_cog" in sys.modules:
            importlib.reload(sys.modules["cogs.shop_cog"])

        from cogs.shop_cog import ShopView as SV
        self.ShopView = SV

    async def test_shop_callback_validation_success(self):
        """Verify that purchase_item_callback accepts valid input."""
        db = Mock()
        user = MagicMock()
        user.id = 12345

        # Instantiate view with mocked dependencies
        view = self.ShopView(db, user, 1000)

        # Mock internal method to avoid DB calls
        # We assume purchase_item_callback is an async method on the view
        # We need to make sure it's awaitable even if we mocked the class components

        # Manually attach AsyncMock to the instance method if it got mocked out
        # But wait, self.ShopView is the real class (imported).
        # So view.purchase_item_callback should be the real method.
        # The error "MagicMock can't be used in await expression" implies
        # view.purchase_item_callback IS a MagicMock.
        # This happens if the View base class or some decoration made it a mock.

        # Let's inspect what ShopView inherits from.
        # In our mock: discord.ui.View = MagicMock()
        # So ShopView inherits from MagicMock.
        # This is dangerous because methods not defined in ShopView might be MagicMocks.
        # BUT purchase_item_callback IS defined in ShopView.

        # Maybe ShopView.purchase_item_callback is being overwritten?
        # Or maybe it's not a coroutine?

        # Let's try to patch get_player_or_error as well since the original test did
        # Mock db.get_player explicitly to return a dict, not a Mock
        db.get_player = MagicMock(return_value={"aurum": 900})

        with patch("cogs.shop_cog.get_player_or_error", new=AsyncMock(return_value={"aurum": 1000})):
            # Mock Interacton
            interaction = MagicMock()
            interaction.user = user
            interaction.data = {"values": ["hp_potion_1:40"]}
            interaction.response = MagicMock()
            interaction.response.defer = AsyncMock()
            interaction.followup = MagicMock()
            interaction.followup.send = AsyncMock()

            # Mock View methods called inside
            # _execute_purchase seems to be a helper method
            view._execute_purchase = Mock(return_value=(True, {"name": "Potion"}, 900))

            # Since interaction is a MagicMock, interaction.edit_original_response is also a MagicMock.
            # But await requires an awaitable (coroutine or Future).
            # MagicMock isn't awaitable by default unless configured.
            interaction.edit_original_response = AsyncMock()

            await view.purchase_item_callback(interaction)

            # Check if it proceeded
            interaction.response.defer.assert_awaited()

    async def test_shop_callback_validation_failure_empty(self):
        """Verify that purchase_item_callback rejects empty input."""
        db = Mock()
        user = MagicMock()
        view = self.ShopView(db, user, 1000)

        interaction = MagicMock()
        interaction.user = user
        interaction.data = {"values": []}  # Empty
        interaction.response = MagicMock()
        interaction.response.defer = AsyncMock()
        interaction.followup = MagicMock()
        interaction.followup.send = AsyncMock()

        # Patch get_player_or_error
        with patch("cogs.shop_cog.get_player_or_error", new=AsyncMock(return_value=True)):
            await view.purchase_item_callback(interaction)

        # Should defer
        interaction.response.defer.assert_awaited()

        # Should send error about invalid selection
        interaction.followup.send.assert_awaited_with("❌ Invalid selection.", ephemeral=True)

    async def test_shop_callback_validation_failure_malformed(self):
        """Verify that purchase_item_callback rejects malformed input."""
        db = Mock()
        user = MagicMock()
        view = self.ShopView(db, user, 1000)

        interaction = MagicMock()
        interaction.user = user
        interaction.data = {"values": [""]}  # Empty string in list
        interaction.response = MagicMock()
        interaction.response.defer = AsyncMock()
        interaction.followup = MagicMock()
        interaction.followup.send = AsyncMock()

        # Patch get_player_or_error
        with patch("cogs.shop_cog.get_player_or_error", new=AsyncMock(return_value=True)):
            await view.purchase_item_callback(interaction)

        interaction.followup.send.assert_awaited_with("❌ Invalid selection.", ephemeral=True)


if __name__ == "__main__":
    unittest.main()
