# Consolidated test file
# Auto-generated by Regression Hunter
import sys
import os
from unittest.mock import MagicMock

# Ensure the project root is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

# Pre-patch dependencies to allow top-level imports during collection
if "pymongo" not in sys.modules:
    sys.modules["pymongo"] = MagicMock()
if "pymongo.errors" not in sys.modules:
    sys.modules["pymongo.errors"] = MagicMock()
if "discord" not in sys.modules:
    sys.modules["discord"] = MagicMock()


from database.database_manager import DatabaseManager  # noqa: E402

from game_systems.guild_system.tournament_system import TournamentSystem  # noqa: E402
from unittest.mock import MagicMock
from unittest.mock import MagicMock, patch
import datetime
import os
import sys
import unittest


# ------------------------------------------------------------
# Merged from test_tournament_system.py
# ------------------------------------------------------------

# Ensure root dir is in path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock pymongo before importing DatabaseManager
# This is required because the pytest environment does not have pymongo installed,
# and DatabaseManager imports it at the module level.
mock_pymongo = MagicMock()
sys.modules["pymongo"] = mock_pymongo
sys.modules["pymongo.errors"] = MagicMock()


class TestTournamentSystem(unittest.TestCase):
    def setUp(self):
        self.mock_db = MagicMock()
        self.system = TournamentSystem(self.mock_db)

    def test_start_weekly_tournament_creates_new(self):
        # Setup: No active tournament
        self.mock_db.get_active_tournament.return_value = None
        self.mock_db.create_tournament.return_value = 101

        # Execute
        t_id = self.system.start_weekly_tournament()

        # Verify
        self.assertEqual(t_id, 101)
        self.mock_db.create_tournament.assert_called_once()
        args = self.mock_db.create_tournament.call_args_list[0]
        # In python 3.8+ call_args is a tuple (args, kwargs) or just use .args
        # checking args
        created_type = args.kwargs.get("type")
        self.assertIn(created_type, self.system.TOURNAMENT_TYPES)

    def test_start_weekly_tournament_returns_existing(self):
        # Setup: Active tournament exists and is valid
        future_end = (datetime.datetime.now() + datetime.timedelta(days=1)).isoformat()
        self.mock_db.get_active_tournament.return_value = {"id": 50, "type": "monster_kills", "end_time": future_end}

        # Execute
        t_id = self.system.start_weekly_tournament()

        # Verify
        self.assertEqual(t_id, 50)
        self.mock_db.create_tournament.assert_not_called()

    def test_record_action_updates_score(self):
        # Setup: Active tournament matches action
        future_end = (datetime.datetime.now() + datetime.timedelta(days=1)).isoformat()
        self.mock_db.get_active_tournament.return_value = {"id": 50, "type": "monster_kills", "end_time": future_end}

        # Execute
        self.system.record_action(12345, "monster_kills", 5)

        # Verify
        self.mock_db.update_tournament_score.assert_called_once_with(12345, 50, 5)

    def test_record_action_ignores_mismatch(self):
        # Setup: Active tournament is quests, action is kills
        future_end = (datetime.datetime.now() + datetime.timedelta(days=1)).isoformat()
        self.mock_db.get_active_tournament.return_value = {"id": 50, "type": "quests_completed", "end_time": future_end}

        # Execute
        self.system.record_action(12345, "monster_kills", 1)

        # Verify
        self.mock_db.update_tournament_score.assert_not_called()

    def test_end_current_tournament_distributes_rewards(self):
        # Setup: Active tournament
        self.mock_db.get_active_tournament.return_value = {"id": 50, "type": "monster_kills"}
        # Mock leaderboard
        self.mock_db.get_tournament_leaderboard.return_value = [
            {"discord_id": 1, "score": 100, "name": "Player1"},
            {"discord_id": 2, "score": 80, "name": "Player2"},
        ]

        # Execute
        result = self.system.end_current_tournament()

        # Verify
        self.mock_db.increment_player_fields.assert_any_call(1, aurum=1000)  # Rank 1
        self.mock_db.increment_player_fields.assert_any_call(2, aurum=500)  # Rank 2
        self.mock_db.add_title.assert_called_with(1, "Grand Champion")
        self.mock_db.end_active_tournament.assert_called_once()
        self.assertIn("Player1", result)


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_tournament_caching.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock pymongo BEFORE import
mock_pymongo = MagicMock()
sys.modules["pymongo"] = mock_pymongo
sys.modules["pymongo.errors"] = MagicMock()


class TestTournamentCaching(unittest.TestCase):
    def setUp(self):
        # Reset singleton state
        DatabaseManager._instance = None
        DatabaseManager._initialized = False

        # Patch MongoClient
        self.client_patcher = patch("database.database_manager.MongoClient")
        self.mock_client_cls = self.client_patcher.start()

        self.mock_client = MagicMock()
        self.mock_client_cls.return_value = self.mock_client

        self.mock_db = MagicMock()
        self.mock_client.__getitem__.return_value = self.mock_db

        # Bridge collection access
        def get_collection(name):
            return getattr(self.mock_db, name)

        self.mock_db.__getitem__.side_effect = get_collection

        # Mock counters collection
        self.mock_db.counters.find_one_and_update.return_value = {"seq": 100}

        self.db = DatabaseManager()

    def tearDown(self):
        self.client_patcher.stop()
        DatabaseManager._instance = None
        DatabaseManager._initialized = False

    def test_tournament_caching(self):
        # Setup mock return
        self.mock_db.tournaments.find_one.return_value = {"type": "spectral_tide", "active": 1}

        # 1. First Call - Should hit DB
        with patch("time.time", return_value=1000.0):
            tourney1 = self.db.get_active_tournament()

        self.assertEqual(tourney1["type"], "spectral_tide")
        self.mock_db.tournaments.find_one.assert_called()
        call_count_after_first = self.mock_db.tournaments.find_one.call_count

        # 2. Second Call (Immediate) - Should NOT hit DB (if cached)
        # We simulate time advancing only slightly (within 60s window)
        with patch("time.time", return_value=1030.0):
            tourney2 = self.db.get_active_tournament()

        self.assertEqual(tourney2["type"], "spectral_tide")

        # Expectation: Call count should remain the same (cached)
        self.assertEqual(self.mock_db.tournaments.find_one.call_count, call_count_after_first, "DB should not be hit again if cached")

    def test_cache_expiration(self):
        self.mock_db.tournaments.find_one.return_value = {"type": "spectral_tide", "active": 1}

        # 1. Populate cache
        with patch("time.time", return_value=1000.0):
            self.db.get_active_tournament()

        self.mock_db.tournaments.find_one.reset_mock()

        # 2. Call after expiration (61s later)
        with patch("time.time", return_value=1061.0):
            self.db.get_active_tournament()

        # Expectation: Called
        self.mock_db.tournaments.find_one.assert_called_once()

    def test_invalidation_create(self):
        self.mock_db.tournaments.find_one.return_value = {"type": "spectral_tide", "active": 1}

        # 1. Populate cache
        with patch("time.time", return_value=1000.0):
            self.db.get_active_tournament()

        self.mock_db.tournaments.find_one.reset_mock()

        # 2. Create new tournament (should invalidate cache)
        with patch("time.time", return_value=1010.0):
            self.db.create_tournament("void_hunt", "start", "end")

        # 3. Fetch again - Should hit DB
        with patch("time.time", return_value=1020.0):
            self.db.get_active_tournament()

        # Expectation: Called
        self.mock_db.tournaments.find_one.assert_called_once()

    def test_invalidation_end(self):
        self.mock_db.tournaments.find_one.return_value = {"type": "spectral_tide", "active": 1}

        # 1. Populate cache
        with patch("time.time", return_value=1000.0):
            self.db.get_active_tournament()

        self.mock_db.tournaments.find_one.reset_mock()

        # 2. End tournament (should invalidate cache)
        with patch("time.time", return_value=1010.0):
            self.db.end_active_tournament()

        # 3. Fetch again - Should hit DB
        with patch("time.time", return_value=1020.0):
            self.db.get_active_tournament()

        # Expectation: Called
        self.mock_db.tournaments.find_one.assert_called_once()

    def test_return_copy(self):
        """Test that the cache returns a copy to prevent mutation."""
        self.mock_db.tournaments.find_one.return_value = {"type": "spectral_tide", "active": 1, "data": {}}

        with patch("time.time", return_value=1000.0):
            tourney1 = self.db.get_active_tournament()

        # Mutate the returned object
        tourney1["mutated"] = True

        # Fetch again
        with patch("time.time", return_value=1010.0):
            tourney2 = self.db.get_active_tournament()

        # The second fetch should NOT have the mutation
        self.assertNotIn("mutated", tourney2)
        self.assertNotEqual(tourney1, tourney2)


if __name__ == "__main__":
    unittest.main()
