# Consolidated test file
# Auto-generated by Regression Hunter
import sys
import os
from unittest.mock import MagicMock

# Ensure the project root is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

# Pre-patch dependencies to allow top-level imports during collection
if "pymongo" not in sys.modules:
    sys.modules["pymongo"] = MagicMock()
if "pymongo.errors" not in sys.modules:
    sys.modules["pymongo.errors"] = MagicMock()
if "discord" not in sys.modules:
    sys.modules["discord"] = MagicMock()


from database.database_manager import DatabaseManager

from database.database_manager import DatabaseManager  # noqa: E402
from unittest.mock import MagicMock
from unittest.mock import MagicMock, patch
import importlib
import os
import sys
import unittest


# ------------------------------------------------------------
# Merged from test_infirmary_exploit.py
# ------------------------------------------------------------

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock pymongo
pymongo = MagicMock()
pymongo.errors = MagicMock()
pymongo.errors.DuplicateKeyError = Exception
sys.modules["pymongo"] = pymongo
sys.modules["pymongo.errors"] = pymongo.errors


class TestInfirmaryFix(unittest.TestCase):
    def setUp(self):
        self.db_manager = DatabaseManager()
        # Clean up any mocks on the singleton from other tests
        if hasattr(self.db_manager, "_col") and isinstance(self.db_manager._col, MagicMock):
            del self.db_manager._col
        self.db_manager.db = MagicMock()

    def test_mp_restore_cost(self):
        # Player state: Full HP, Missing MP
        max_hp = 100
        max_mp = 50
        current_hp = 100
        current_mp = 10  # Missing 40 MP
        aurum = 200

        player_doc = {"current_hp": current_hp, "current_mp": current_mp, "aurum": aurum}

        # Mock find_one
        self.db_manager.db["players"].find_one.return_value = player_doc

        # Mock update_one
        mock_res = MagicMock()
        mock_res.modified_count = 1
        self.db_manager.db["players"].update_one.return_value = mock_res

        success, msg = self.db_manager.execute_heal(123, max_hp, max_mp, 0)

        # Verify
        self.assertTrue(success)

        # Calculate expected cost
        # Missing MP = 40. Cost = 40 * 3.0 = 120.
        expected_cost = 120
        self.assertIn(f"Restored HP/MP for {expected_cost} Aurum", msg)

        # Verify update_one called with correct aurum deduction
        args, kwargs = self.db_manager.db["players"].update_one.call_args
        update_op = args[1]
        self.assertEqual(update_op["$inc"]["aurum"], -expected_cost)

    def test_hp_restore_cost(self):
        # Player state: Missing HP, Full MP
        max_hp = 100
        max_mp = 50
        current_hp = 50  # Missing 50 HP
        current_mp = 50
        aurum = 200

        player_doc = {"current_hp": current_hp, "current_mp": current_mp, "aurum": aurum}

        # Mock find_one
        self.db_manager.db["players"].find_one.return_value = player_doc
        # Mock update_one
        mock_res = MagicMock()
        mock_res.modified_count = 1
        self.db_manager.db["players"].update_one.return_value = mock_res

        success, msg = self.db_manager.execute_heal(123, max_hp, max_mp, 0)

        # Missing HP = 50. Cost = 50 * 2.0 = 100.
        expected_cost = 100
        self.assertIn(f"Restored HP/MP for {expected_cost} Aurum", msg)


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_infirmary_fallback.py
# ------------------------------------------------------------

# Fix path to include repo root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Helper Mocks
class MockView:
    def __init__(self, timeout=180):
        pass

    def add_item(self, item):
        pass

    def clear_items(self):
        pass


class MockButton:
    def __init__(self, label=None, style=None, custom_id=None, emoji=None, row=None, disabled=False):
        self.callback = None
        self.label = label

    def _is_v2(self):
        return False


class TestInfirmaryFallbackExploit(unittest.TestCase):
    def setUp(self):
        # Patch sys.modules
        self.modules_patcher = patch.dict(sys.modules)
        self.modules_patcher.start()

        # Mock Discord
        mock_discord = MagicMock()
        mock_discord.ui.View = MockView
        mock_discord.ui.Button = MockButton
        mock_discord.ButtonStyle = MagicMock()
        mock_discord.User = MagicMock()
        mock_discord.Embed = MagicMock()
        mock_discord.Color = MagicMock()

        sys.modules["discord"] = mock_discord
        sys.modules["discord.ui"] = mock_discord.ui
        sys.modules["discord.ext"] = MagicMock()
        sys.modules["discord.ext.commands"] = MagicMock()

        # Mock Pymongo
        sys.modules["pymongo"] = MagicMock()
        sys.modules["pymongo.errors"] = MagicMock()

        # Import modules under test
        import cogs.infirmary_cog

        importlib.reload(cogs.infirmary_cog)

        self.InfirmaryView = cogs.infirmary_cog.InfirmaryView

        from game_systems.player.player_stats import PlayerStats

        self.PlayerStats = PlayerStats

        self.mock_db = MagicMock()
        self.user = MagicMock()
        self.user.id = 12345
        self.initial_p_data = {"current_hp": 10, "current_mp": 10, "aurum": 1000}

        # Initial stats: Max HP 100
        self.stale_stats = self.PlayerStats(str_base=1, end_base=5)
        # Check max_hp
        assert self.stale_stats.max_hp == 100, f"Setup error: Expected 100 HP, got {self.stale_stats.max_hp}"

    def tearDown(self):
        self.modules_patcher.stop()

    def test_fallback_vulnerability(self):
        """
        Scenario:
        1. View created with stale stats (Max HP 100).
        2. Player actually has Max HP 50 in reality (e.g. unequipped items).
        3. DB fetch for fresh stats FAILS (returns None/Empty).
        4. Vulnerability: View falls back to stale stats (100) and heals player to 100.
           Result: Player has 50 extra HP they shouldn't have.
        """

        # 1. Create View with stale stats
        view = self.InfirmaryView(self.mock_db, self.user, self.initial_p_data, self.stale_stats)

        # 2. Simulate DB failure for stats
        self.mock_db.get_player_stats_json.return_value = None
        self.mock_db.execute_heal.return_value = (True, "Healed")

        # 3. Execute Heal
        success, msg = view._execute_heal()

        # 4. Assert Fix
        self.assertFalse(success, "Heal should fail if stats cannot be fetched")
        self.assertIn("System error", msg, "Should return an error message")

        # Ensure execute_heal was NOT called
        self.mock_db.execute_heal.assert_not_called()
        print("\nSUCCESS: Vulnerability patched. Heal rejected on missing stats.")


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_infirmary_race.py
# ------------------------------------------------------------


class TestInfirmaryRace(unittest.TestCase):
    def setUp(self):
        self.mock_db_client = MagicMock()
        self.mock_db = MagicMock()
        self.mock_db_client.__getitem__.return_value = self.mock_db

        # Patch the client creation in DatabaseManager
        # We can't easily patch the class attribute _instance, so we'll mock the internals
        self.db = DatabaseManager()
        self.db._client = self.mock_db_client
        self.db.db = self.mock_db
        self.db._col = MagicMock()

    def test_execute_heal_uses_atomic_inc(self):
        """Test that execute_heal uses $inc for aurum to prevent lost updates."""

        # Mock finding the player
        # Initial state: 50 HP, 1000 Gold
        self.db._col("players").find_one.return_value = {
            "discord_id": 12345,
            "current_hp": 50,
            "current_mp": 10,
            "aurum": 1000,
        }

        # Mock update result to simulate success
        mock_result = MagicMock()
        mock_result.modified_count = 1
        self.db._col("players").update_one.return_value = mock_result

        # Call execute_heal
        # Target: 150 HP (Missing 100). Cost should be 200 (2.0 * 100)
        # Target: 50 MP (Missing 40). Cost should be 120 (3.0 * 40)
        # Total Cost: 320
        result, msg = self.db.execute_heal(12345, max_hp=150, max_mp=50, cost=0)

        self.assertTrue(result)
        self.assertIn("Restored HP/MP", msg)

        # Check the update_one call
        args, kwargs = self.db._col("players").update_one.call_args
        filter_query = args[0]
        update_op = args[1]

        # 1. Verify Optimistic Locking: Filter should include current_hp
        self.assertEqual(filter_query["current_hp"], 50, "Update should filter by previous HP (Optimistic Locking)")

        # 2. Verify Atomic Increment: Update should use $inc for aurum
        self.assertIn("$inc", update_op, "Update should use $inc for atomic balance deduction")
        self.assertEqual(update_op["$inc"]["aurum"], -320, "Should deduct 320 aurum")

        # 3. Verify Vitals Set: Update should use $set for HP/MP
        self.assertIn("$set", update_op)
        self.assertEqual(update_op["$set"]["current_hp"], 150)

    def test_execute_heal_handles_race_condition(self):
        """Test that execute_heal fails if HP changes between fetch and update."""

        # Mock finding the player
        self.db._col("players").find_one.return_value = {
            "discord_id": 12345,
            "current_hp": 50,
            "current_mp": 10,
            "aurum": 1000,
        }

        # Mock update result to simulate FAILURE (modified_count = 0)
        # This happens if the filter (current_hp=50) doesn't match DB anymore
        mock_result = MagicMock()
        mock_result.modified_count = 0
        self.db._col("players").update_one.return_value = mock_result

        # Call execute_heal
        result, msg = self.db.execute_heal(12345, max_hp=150, max_mp=50, cost=0)

        # Should return False because update failed
        self.assertFalse(result)
        self.assertEqual(msg, "Healing failed due to state change. Please try again.")


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_infirmary_security.py
# ------------------------------------------------------------

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Helper Mocks
class MockView:
    def __init__(self, timeout=180):
        pass

    def add_item(self, item):
        pass

    def clear_items(self):
        pass


class MockButton:
    def __init__(self, label=None, style=None, custom_id=None, emoji=None, row=None, disabled=False):
        self.callback = None
        self.label = label

    def _is_v2(self):
        return False


class TestInfirmaryStateIssue(unittest.TestCase):
    def setUp(self):
        # Patch sys.modules
        self.modules_patcher = patch.dict(sys.modules)
        self.modules_patcher.start()

        # Mock Discord
        mock_discord = MagicMock()
        mock_discord.ui.View = MockView
        mock_discord.ui.Button = MockButton
        mock_discord.ButtonStyle = MagicMock()
        mock_discord.User = MagicMock()
        mock_discord.Embed = MagicMock()
        mock_discord.Color = MagicMock()

        sys.modules["discord"] = mock_discord
        sys.modules["discord.ui"] = mock_discord.ui
        sys.modules["discord.ext"] = MagicMock()
        sys.modules["discord.ext.commands"] = MagicMock()

        # Mock Pymongo
        mock_pymongo = MagicMock()
        mock_pymongo.errors = MagicMock()
        mock_pymongo.errors.DuplicateKeyError = Exception  # Preserve original mock behavior

        sys.modules["pymongo"] = mock_pymongo
        sys.modules["pymongo.errors"] = mock_pymongo.errors

        # Import module under test
        import cogs.infirmary_cog

        importlib.reload(cogs.infirmary_cog)
        self.InfirmaryView = cogs.infirmary_cog.InfirmaryView

        from database.database_manager import DatabaseManager

        self.DatabaseManager = DatabaseManager

        from game_systems.player.player_stats import PlayerStats

        self.PlayerStats = PlayerStats

        # Setup test objects
        self.mock_db = MagicMock(spec=self.DatabaseManager)
        self.user = MagicMock()
        self.user.id = 12345

        # Initial Player Data (for View initialization)
        self.initial_p_data = {"current_hp": 50, "current_mp": 10, "aurum": 1000}

        # Initial Stats (Max HP 150 based on base stats logic in PlayerStats)
        # PlayerStats(str_base=10, end_base=10) -> HP = 50 + (10 * 10) = 150
        self.initial_stats = self.PlayerStats(str_base=10, end_base=10)

    def tearDown(self):
        self.modules_patcher.stop()

    def test_stale_stats_healing(self):
        """
        Scenario:
        1. View initialized with Max HP 150.
        2. Player changes gear/buffs, Max HP becomes 200 in DB (simulated).
        3. User clicks Heal.
        4. View SHOULD heal to 200 (Fresh), but due to bug heals to 150 (Stale).
        """

        # 1. Initialize View with initial stats (Max HP 150)
        view = self.InfirmaryView(self.mock_db, self.user, self.initial_p_data, self.initial_stats)

        old_max_hp = self.initial_stats.max_hp  # 150
        new_max_hp = 200  # Simulated new Max HP in DB

        # 2. Simulate DB state where player has changed

        # Mock get_player_vitals (Current state)
        self.mock_db.get_player_vitals.return_value = {"current_hp": 50, "current_mp": 10}
        self.mock_db.get_player_field.return_value = 1000  # Aurum

        # Mock get_player_stats_json to return FRESH stats (Max HP 200)
        fresh_stats = self.PlayerStats(str_base=10, end_base=15)  # END 15 -> HP 200
        self.mock_db.get_player_stats_json.return_value = fresh_stats.to_dict()

        # 3. Call _execute_heal
        view._execute_heal()

        # 4. Verify execute_heal called with FRESH Max HP (200)
        self.mock_db.execute_heal.assert_called_with(self.user.id, new_max_hp, fresh_stats.max_mp, cost=0)

        # Also ensure it wasn't called with old HP
        args, _ = self.mock_db.execute_heal.call_args
        self.assertEqual(
            args[1], new_max_hp, f"Vulnerability: Healed to {args[1]} (Stale), expected {new_max_hp} (Fresh)"
        )


if __name__ == "__main__":
    unittest.main()
