# Consolidated test file
# Auto-generated by Regression Hunter
import sys
import os
from unittest.mock import MagicMock

# Ensure the project root is in sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))

# Pre-patch dependencies to allow top-level imports during collection
if "pymongo" not in sys.modules:
    sys.modules["pymongo"] = MagicMock()
if "pymongo.errors" not in sys.modules:
    sys.modules["pymongo.errors"] = MagicMock()
if "discord" not in sys.modules:
    sys.modules["discord"] = MagicMock()


# Now import the modules
from game_systems.adventure.combat_handler import CombatHandler  # noqa: E402
from database.database_manager import DatabaseManager  # noqa: E402

from game_systems.combat.combat_engine import CombatEngine

from game_systems.combat.combat_engine import CombatEngine  # noqa: E402

from game_systems.combat.damage_formula import DamageFormula
from game_systems.player.level_up import LevelUpSystem  # noqa: E402
from game_systems.player.player_stats import PlayerStats
from game_systems.player.player_stats import PlayerStats  # noqa: E402
from unittest.mock import MagicMock
from unittest.mock import MagicMock, patch
import os
import sys
import unittest


# ------------------------------------------------------------
# Merged from test_combat_actions.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock external dependencies
sys.modules["pymongo"] = MagicMock()
sys.modules["discord"] = MagicMock()


class TestCombatActions(unittest.TestCase):
    def setUp(self):
        self.stats = PlayerStats(str_base=10, end_base=10, dex_base=10, agi_base=10, mag_base=10)
        self.player_wrapper = MagicMock(spec=LevelUpSystem)
        self.player_wrapper.stats = self.stats
        self.player_wrapper.level = 1
        self.player_wrapper.hp_current = 50
        self.player_wrapper.hp_max = 100

        self.monster = {
            "name": "Test Monster",
            "HP": 1000,
            "max_hp": 1000,
            "MP": 10,
            "ATK": 20,  # High attack to test mitigation
            "DEF": 0,
            "level": 1,
            "tier": "Normal",
            "skills": [],
        }

    def test_defend_action(self):
        """Test that Defend action reduces damage and restores MP."""
        current_mp = 10
        max_mp = 100
        stats = {"MP": 100, "HP": 100, "END": 10, "AGI": 10}

        # Instantiate CombatEngine
        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[],
            player_mp=current_mp,
            player_class_id=1,
            stats_dict=stats,
            action="defend",
        )

        # Mock RNG
        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        # Verify MP Restoration (5% of 100 = 5)
        # Note: If previous logic was correct, MP becomes 15
        expected_mp = 15
        self.assertEqual(result["mp_current"], expected_mp, "Defend should restore 5% MP")

        # Verify Damage Mitigation
        damage_defended = result["turn_report"]["damage_taken"]

        # Run again with "attack" to compare
        engine_attack = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[],
            player_mp=current_mp,
            player_class_id=1,
            stats_dict=stats,
            action="attack",
        )

        # Patch _decide_player_skill so we force a basic attack
        engine_attack._decide_player_skill = MagicMock(return_value={"skill": None})

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result_attack = engine_attack.run_combat_turn()

        damage_attacked = result_attack["turn_report"]["damage_taken"]

        self.assertTrue(damage_defended < damage_attacked, "Defend should reduce damage")
        self.assertAlmostEqual(damage_defended, int(damage_attacked * 0.5), delta=1)

    def test_flee_failed_action(self):
        """Test that Flee Failed results in player skip and monster attack."""
        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster,
            player_skills=[],
            player_mp=10,
            player_class_id=1,
            stats_dict={"MP": 100, "END": 10, "AGI": 10},
            action="flee_failed",
        )

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        self.assertEqual(result["turn_report"]["str_hits"], 0, "Player should not attack on flee fail")
        self.assertTrue(result["turn_report"]["damage_taken"] > 0, "Monster should attack")

    def test_special_ability_action(self):
        """Test that Special Ability action uses MP and deals boosted damage."""
        current_mp = 50
        max_mp = 100
        stats = {"MP": 100, "HP": 100, "STR": 20, "END": 10, "AGI": 10, "MAG": 10, "LCK": 10}

        # Warrior (Class 1) -> Cleave (1.5x DMG)
        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[],
            player_mp=current_mp,
            player_class_id=1,
            stats_dict=stats,
            action="special_ability",
        )

        # Mock RNG to ensure hit and standard variance
        with patch("random.random", return_value=0.9):  # No crit
            with patch("random.uniform", return_value=1.0):  # No variance
                # Run Special
                result_special = engine.run_combat_turn()

        # Check MP Deduction (Cost 20)
        self.assertEqual(result_special["mp_current"], 30, "Special Ability should cost 20 MP")

        # Check Damage
        # Compare with normal attack
        engine_normal = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[],
            player_mp=current_mp,
            player_class_id=1,
            stats_dict=stats,
            action="attack",
        )

        # Force basic attack
        engine_normal._decide_player_skill = MagicMock(return_value={"skill": None})

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result_normal = engine_normal.run_combat_turn()

        dmg_special = 1000 - result_special["monster_hp"]
        dmg_normal = 1000 - result_normal["monster_hp"]

        # Verify damage happened
        self.assertTrue(dmg_special > 0, "Special attack should deal damage")
        self.assertTrue(dmg_normal > 0, "Normal attack should deal damage")

        # Expected: Special ~ 1.5 * Normal
        # Allow small delta for integer rounding
        self.assertAlmostEqual(dmg_special, int(dmg_normal * 1.5), delta=1)


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_combat_counter.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

class TestCombatCounter(unittest.TestCase):
    def setUp(self):
        self.player = MagicMock()
        self.player.hp_current = 100
        self.player.stats.max_hp = 100
        self.player.stats.get_total_stats_dict.return_value = {"HP": 100, "MP": 100, "ATK": 10, "DEF": 10}
        self.player.level = 1

        self.monster = {
            "name": "Test Monster",
            "HP": 100,
            "max_hp": 100,
            "MP": 100,
            "ATK": 20,
            "DEF": 5,
            "skills": []
        }

    def test_parry_physical_charge(self):
        # Setup Physical Charge
        self.monster["charged_skill"] = {"name": "Smash", "type": "physical", "power": 2.0}

        engine = CombatEngine(
            player=self.player,
            monster=self.monster,
            player_skills=[],
            player_mp=100,
            player_class_id=1,
            action="defend"
        )

        result = engine.run_combat_turn()

        # Verify Parry
        phrases = " ".join(result["phrases"])
        self.assertIn("PARRIED!", phrases)
        self.assertIn("Reflected!", phrases)
        self.assertIn("misses its turn", phrases) # Monster should be stunned
        self.assertLess(result["monster_hp"], 100) # Monster took reflect damage
        self.assertNotIn("unleashes **Smash**", phrases) # Charge cancelled

    def test_interrupt_magical_charge(self):
        # Setup Magical Charge
        self.monster["charged_skill"] = {"name": "Doom", "type": "magical", "power": 2.0}

        engine = CombatEngine(
            player=self.player,
            monster=self.monster,
            player_skills=[],
            player_mp=100,
            player_class_id=1,
            action="attack"
        )

        result = engine.run_combat_turn()

        # Verify Interrupt
        phrases = " ".join(result["phrases"])
        self.assertIn("INTERRUPTED!", phrases)
        self.assertIn("misses its turn", phrases)
        self.assertNotIn("unleashes **Doom**", phrases)
        # Should be a crit
        self.assertEqual(result["turn_report"]["player_crit"], 1)

    def test_fail_counter_wrong_action(self):
        # Setup Physical Charge but Player Attacks (Wrong)
        self.monster["charged_skill"] = {"name": "Smash", "type": "physical", "power": 2.0}

        engine = CombatEngine(
            player=self.player,
            monster=self.monster,
            player_skills=[],
            player_mp=100,
            player_class_id=1,
            action="attack"
        )

        result = engine.run_combat_turn()

        phrases = " ".join(result["phrases"])
        self.assertNotIn("PARRIED!", phrases)
        self.assertNotIn("INTERRUPTED!", phrases)
        # Monster should execute charge
        self.assertIn("unleashes **Smash**", phrases)

if __name__ == '__main__':
    unittest.main()


# ------------------------------------------------------------
# Merged from test_combat_crash.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock external dependencies
pymongo_mock = MagicMock()
pymongo_errors_mock = MagicMock()
pymongo_mock.errors = pymongo_errors_mock
sys.modules["pymongo"] = pymongo_mock
sys.modules["pymongo.errors"] = pymongo_errors_mock
sys.modules["discord"] = MagicMock()


class TestCombatCrash(unittest.TestCase):
    def test_resolve_turn_db_failure(self):
        """Test that resolve_turn handles database failures without crashing due to UnboundLocalError."""

        # Instantiate handler with a mocked DB
        db_mock = MagicMock(spec=DatabaseManager)

        # Simulate DB failure early in the process
        db_mock.get_player_stats_json.side_effect = Exception("Database Connection Failed")

        handler = CombatHandler(db_mock, 12345)

        active_monster = {"HP": 100, "max_hp": 100}
        battle_report = CombatHandler.create_empty_battle_report()

        try:
            result = handler.resolve_turn(
                active_monster=active_monster,
                battle_report=battle_report,
                accumulated_exp=0
            )

            # If we reach here, we check if the result is valid
            print(f"Result: {result}")
            self.assertIsNone(result["winner"])
            self.assertEqual(result["phrases"][0], "*Something disrupts the flow of battle...*")

        except UnboundLocalError as e:
            # THIS IS EXPECTED TO FAIL currently
            print(f"Caught expected UnboundLocalError: {e}")
            raise  # Re-raise to fail the test and confirm the bug
        except Exception as e:
            self.fail(f"CombatHandler crashed with unexpected exception: {e}")

if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_combat_defense_curve.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class TestCombatDefenseCurve(unittest.TestCase):
    def setUp(self):
        # Setup basic player stats
        self.stats = PlayerStats(str_base=10, end_base=10, mag_base=10, dex_base=10, agi_base=10, lck_base=10)
        # STR=10 -> Bonus = 10 * 2.0 = 20
        # DEX=10 -> Bonus = 10 * 1.0 = 10
        # MAG=10 -> Bonus = 10 * 0.5 = 5
        # Attack Power = 35

    def test_player_attack_defense_reduction(self):
        """
        Verify that monster Defense reduces player damage according to the formula:
        reduction = DEF * (0.3 + 0.2 * min(1, DEF/100))
        """
        base_ap = 35  # Calculated from setup

        # Test Cases: (Monster DEF, Expected Reduction, Expected Damage)
        # 1. DEF = 0 -> Red = 0 * 0.3 = 0. Dmg = 35.
        # 2. DEF = 50 -> Red = 50 * (0.3 + 0.1) = 20. Dmg = 15.
        # 3. DEF = 100 -> Red = 100 * (0.3 + 0.2) = 50. Dmg = 1 (Floor).
        # 4. DEF = 200 -> Red = 200 * 0.5 = 100. Dmg = 1 (Floor).

        test_cases = [
            (0, 35),
            (50, 15),
            (100, 1), # 35 - 50 < 1 -> 1
            (200, 1)
        ]

        with patch("random.uniform", return_value=1.0), \
             patch("random.random", return_value=0.5): # No crit

            for def_val, expected_dmg in test_cases:
                monster = {"DEF": def_val}
                dmg, is_crit, _ = DamageFormula.player_attack(self.stats, monster)

                self.assertEqual(dmg, expected_dmg,
                    f"Failed for DEF={def_val}. Expected {expected_dmg}, got {dmg}")
                self.assertFalse(is_crit)

    def test_monster_attack_player_defense_scaling(self):
        """
        Verify that player END scales defense and reduces monster damage.
        Player Defense = END * 1.5 (Tier 1)
        """
        # Monster ATK = 100
        monster = {"ATK": 100}

        # Test Cases: (Player END, Expected Defense, Expected Reduction, Expected Damage)
        # 1. END = 10 -> Def = 15. Red = 15 * (0.3 + 0.2*0.15) = 15 * 0.33 = 4.95 -> 4.95.
        #    Dmg = 100 - 4.95 = 95.05 -> 95.
        #    Chip Floor = 100 * 0.05 = 5. 95 > 5.

        # 2. END = 100 -> Def = 150. Red = 150 * 0.5 = 75.
        #    Dmg = 100 - 75 = 25.

        # 3. END = 200 -> Def = 337 (Tiered Bonus logic: 100*1.5 + 100*1.5*1.25 = 150 + 187.5 = 337.5 -> 337).
        #    Red = 337 * 0.5 = 168.5.
        #    Base Dmg = 100 - 168.5 < 0.
        #    Chip Floor = 5.
        #    Final Dmg = 5.

        # Let's verify END=10 math carefully.
        # Def = 15.
        # min(1, 15/100) = 0.15.
        # Mul = 0.3 + 0.2 * 0.15 = 0.3 + 0.03 = 0.33.
        # Red = 15 * 0.33 = 4.95.
        # Dmg = 100 - 4.95 = 95.05 -> int(95.05) = 95.

        test_cases = [
            (10, 95),
            (100, 25),
            (200, 5)  # Chip damage floor
        ]

        with patch("random.uniform", return_value=1.0), \
             patch("random.random", return_value=0.5): # No dodge, no crit

            for end_val, expected_dmg in test_cases:
                # Update stats
                self.stats._stats["END"].base = end_val
                # Recalculate bonuses if needed (PlayerStats doesn't cache derived stats so it's fine)

                dmg, is_crit, _ = DamageFormula.monster_attack(monster, self.stats)

                self.assertEqual(dmg, expected_dmg,
                    f"Failed for END={end_val}. Expected {expected_dmg}, got {dmg}")

    def test_monster_chip_damage_floor(self):
        """
        Verify the 5% chip damage floor explicitly.
        """
        monster = {"ATK": 100}

        # Set player END high enough to negate all damage
        # ATK 100. Need Red > 100.
        # If END=200, Red=168.
        self.stats._stats["END"].base = 200

        with patch("random.uniform", return_value=1.0), \
             patch("random.random", return_value=0.5):

            dmg, _, _ = DamageFormula.monster_attack(monster, self.stats)

            expected_chip = int(100 * 0.05) # 5
            self.assertEqual(dmg, expected_chip,
                f"Chip damage should be {expected_chip}, got {dmg}")

    def test_crit_multiplier(self):
        """
        Verify crit multiplier is 1.75x for players.
        """
        base_ap = 35 # Setup default
        monster = {"DEF": 0}

        # Force Crit
        # Damage = 35 * 1.75 = 61.25 -> 61

        with patch("random.uniform", return_value=1.0), \
             patch("random.random", return_value=0.0): # Force Crit (0.0 < chance)

             dmg, is_crit, event = DamageFormula.player_attack(self.stats, monster)

             self.assertTrue(is_crit)
             self.assertEqual(event, "crit")
             self.assertEqual(dmg, 61)

if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_combat_skill_selection.py
# ------------------------------------------------------------

# Add repo root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Mock external dependencies
sys.modules["pymongo"] = MagicMock()
sys.modules["discord"] = MagicMock()


class TestCombatSkillSelection(unittest.TestCase):
    def setUp(self):
        self.stats = PlayerStats(str_base=10, end_base=10, dex_base=10, agi_base=10, mag_base=10)
        self.player_wrapper = MagicMock(spec=LevelUpSystem)
        self.player_wrapper.stats = self.stats
        self.player_wrapper.level = 1
        self.player_wrapper.hp_current = 50
        self.player_wrapper.hp_max = 100

        self.monster = {
            "name": "Test Monster",
            "HP": 1000,
            "max_hp": 1000,
            "MP": 10,
            "ATK": 20,
            "DEF": 0,
            "level": 1,
            "tier": "Normal",
            "skills": [],
        }

        self.fireball_skill = {
            "key_id": "fireball",
            "name": "Fireball",
            "type": "Active",
            "skill_level": 1,
            "mp_cost": 10,
            "power_multiplier": 1.5,
            "heal_power": 0,
            "buff_data": None,
            "scaling_stat": "MAG",
            "scaling_factor": 1.0,
        }

        self.heal_skill = {
            "key_id": "minor_heal",
            "name": "Minor Heal",
            "type": "Active",
            "skill_level": 1,
            "mp_cost": 5,
            "power_multiplier": 0,
            "heal_power": 20,
            "buff_data": None,
            "scaling_stat": "MAG",
            "scaling_factor": 1.0,
        }

    def test_explicit_skill_usage(self):
        """Test that action='skill:fireball' uses the skill correctly."""
        current_mp = 20
        stats = {"MP": 100, "HP": 100, "MAG": 20}

        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[self.fireball_skill],
            player_mp=current_mp,
            player_class_id=2,  # Mage
            stats_dict=stats,
            action="skill:fireball",
        )

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        # Check MP Deduction
        self.assertEqual(result["mp_current"], 10, "Fireball should cost 10 MP")

        # Check that skill was used (log or damage)
        self.assertIn("mag_hits", result["turn_report"], "Fireball should register as mag_hit")
        self.assertTrue(result["turn_report"]["skills_used"] > 0, "Skill usage should be tracked")

        # Verify damage > 0
        self.assertTrue(result["monster_hp"] < 1000, "Monster should take damage from fireball")

    def test_explicit_heal_usage(self):
        """Test that action='skill:minor_heal' heals the player."""
        current_mp = 20
        stats = {"MP": 100, "HP": 100, "MAG": 20}
        self.player_wrapper.hp_current = 50

        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[self.heal_skill],
            player_mp=current_mp,
            player_class_id=4,  # Cleric
            stats_dict=stats,
            action="skill:minor_heal",
        )

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        # Check MP Deduction
        self.assertEqual(result["mp_current"], 15, "Heal should cost 5 MP")

        # Check Healing
        self.assertTrue(result["hp_current"] > 50, "Player should be healed")
        self.assertIn("Minor Heal", str(result["phrases"]), "Log should mention restoration")

    def test_insufficient_mp_fallback(self):
        """Test fallback to basic attack if MP is insufficient."""
        current_mp = 5  # Fireball costs 10
        stats = {"MP": 100, "HP": 100, "MAG": 20}

        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[self.fireball_skill],
            player_mp=current_mp,
            player_class_id=2,
            stats_dict=stats,
            action="skill:fireball",
        )

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        # MP should NOT be deducted (or maybe just for basic attack? Basic attack is 0 MP)
        self.assertEqual(result["mp_current"], 5, "MP should not change on fallback")

        # Should be a basic attack (str_hits or mag_hits depending on class default attack, Mage is mag)
        # But specifically not a skill usage
        self.assertEqual(result["turn_report"]["skills_used"], 0, "Skill should not be used")

        # Log should mention failure
        log_str = "".join([str(p) for p in result["phrases"]])
        self.assertIn("Not enough MP", log_str, "Log should warn about MP")

    def test_unknown_skill_fallback(self):
        """Test fallback if skill key is not found."""
        current_mp = 20
        stats = {"MP": 100, "HP": 100, "MAG": 20}

        engine = CombatEngine(
            player=self.player_wrapper,
            monster=self.monster.copy(),
            player_skills=[self.fireball_skill],
            player_mp=current_mp,
            player_class_id=2,
            stats_dict=stats,
            action="skill:unknown_skill",
        )

        with patch("random.random", return_value=0.9):
            with patch("random.uniform", return_value=1.0):
                result = engine.run_combat_turn()

        self.assertEqual(result["mp_current"], 20, "MP should not change")
        self.assertEqual(result["turn_report"]["skills_used"], 0, "Skill should not be used")

        log_str = "".join([str(p) for p in result["phrases"]])
        self.assertIn("Skill Failed", log_str, "Log should warn about unknown skill")


if __name__ == "__main__":
    unittest.main()


# ------------------------------------------------------------
# Merged from test_combat_special_exploit.py
# ------------------------------------------------------------

# Ensure game_systems can be imported
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

class TestCombatSpecialExploit(unittest.TestCase):
    def setUp(self):
        # Create a mock player with Class 5 (Ranger)
        self.player = MagicMock()
        self.player.level = 10
        self.player.stats = PlayerStats(str_base=10, dex_base=50) # Decent DEX
        self.player.hp_current = 100

        # Monster Data
        self.monster = {
            "name": "Test Monster",
            "HP": 1000,
            "max_hp": 1000,
            "DEF": 0, # 0 Def for easier damage calculation
            "drops": []
        }

        # Mock Player Stats Dict
        self.stats_dict = self.player.stats.get_total_stats_dict()

        # Initialize Combat Engine
        self.engine = CombatEngine(
            player=self.player,
            monster=self.monster,
            player_skills=[],
            player_mp=100,
            player_class_id=5, # Ranger (Has "Aimed Shot")
            active_boosts={},
            stats_dict=self.stats_dict,
            action="special_ability",
            player_stance="balanced"
        )

    @patch('game_systems.combat.combat_engine.DamageFormula')
    @patch('game_systems.combat.combat_engine.random')
    def test_aimed_shot_force_crit_bug(self, mock_random, mock_formula):
        """
        Test that 'Aimed Shot' (Class 5) correctly applies Force Crit damage (1.5x)
        even when the internal 'crit_bonus' RNG roll fails.
        """
        # Setup Mocks

        # 1. Mock DamageFormula.player_attack to return constant damage
        # We use a wrapper to match signature: (player_stats, monster)
        # Returns (damage, is_crit, event_type)
        BASE_DMG = 100
        mock_formula.player_attack.return_value = (BASE_DMG, False, "hit")

        # 2. Mock Random for 'crit_bonus' check in Aimed Shot
        # Aimed Shot has 'crit_bonus': 50 (50% chance).
        # We want it to FAIL (return 51 > 50).
        # mock_random.randint is used for:
        #   - CombatEngine.PLAYER_SKILL_CHANCE (ignored here)
        #   - Aimed Shot crit_bonus check (We want > 50)
        mock_random.randint.return_value = 60

        # 3. Capture 'log' and 'turn_report'
        log = []
        turn_report = {
            "str_hits": 0, "dex_hits": 0, "mag_hits": 0,
            "player_crit": 0, "player_dodge": 0,
            "damage_taken": 0, "skills_used": 0,
            "skill_key_used": None, "hits_taken": 0
        }

        # Execution
        # We call _resolve_special_ability with force_crit=True (Simulating Interrupt)
        self.engine._resolve_special_ability(log, turn_report, force_crit=True)

        # Verification
        # Expected Damage:
        # Base: 100
        # Class 5 Multiplier: 1.5 -> 150
        # Force Crit Multiplier: 1.5 -> 225
        # (Assuming force_crit works)

        # Actual Calculation in Buggy Code:
        # Base: 100
        # Class 5 Multiplier: 150
        # Aimed Shot crit_bonus roll: 60 (Fail)
        # force_crit check: skipped because `spec.get("crit_bonus")` is present.
        # Result: 150.

        initial_hp = 1000
        final_hp = self.engine.monster_hp
        damage_dealt = initial_hp - final_hp

        print(f"Damage Dealt: {damage_dealt}")

        # We expect 225 if fixed, 150 if broken.
        self.assertEqual(damage_dealt, 225, f"Damage should be boosted by force_crit (1.5x) to 225, but was {damage_dealt}")

if __name__ == '__main__':
    unittest.main()
