"""
monster_skills.py

Definitions for monster-specific skills.
Used to populate monster data in game_systems/data/monsters.py.
"""

MONSTER_SKILLS = {
    # Physical Attacks
    "heavy_blow": {
        "key_id": "heavy_blow",
        "name": "Heavy Blow",
        "power": 1.5,
        "mp_cost": 5,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "rapid_strike": {
        "key_id": "rapid_strike",
        "name": "Rapid Strike",
        "power": 1.2,
        "mp_cost": 3,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "crushing_slam": {
        "key_id": "crushing_slam",
        "name": "Crushing Slam",
        "power": 1.8,
        "mp_cost": 8,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "vicious_bite": {
        "key_id": "vicious_bite",
        "name": "Vicious Bite",
        "power": 1.3,
        "mp_cost": 4,
        "type": "physical",
        "desc_key": "bite",
    },
    "crystal_shard": {
        "key_id": "crystal_shard",
        "name": "Crystal Shard",
        "power": 1.4,
        "mp_cost": 6,
        "type": "physical",
        "desc_key": "special_hit",
    },
    # Magical / Elemental
    "prism_beam": {
        "key_id": "prism_beam",
        "name": "Prism Beam",
        "power": 1.8,
        "mp_cost": 12,
        "type": "magical",
        "desc_key": "magic",
    },
    "ember": {
        "key_id": "ember",
        "name": "Ember",
        "power": 1.4,
        "mp_cost": 5,
        "type": "magical",
        "desc_key": "fire",
    },
    "flame_breath": {
        "key_id": "flame_breath",
        "name": "Flame Breath",
        "power": 1.7,
        "mp_cost": 10,
        "type": "magical",
        "desc_key": "fire",
    },
    "poison_spit": {
        "key_id": "poison_spit",
        "name": "Poison Spit",
        "power": 1.1,
        "mp_cost": 5,
        "type": "physical",
        "desc_key": "poison",
    },
    "ice_shard": {
        "key_id": "ice_shard",
        "name": "Ice Shard",
        "power": 1.4,
        "mp_cost": 6,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "frost_breath": {
        "key_id": "frost_breath",
        "name": "Frost Breath",
        "power": 1.6,
        "mp_cost": 10,
        "type": "magical",
        "desc_key": "magic",
    },
    "glacial_roar": {
        "key_id": "glacial_roar",
        "name": "Glacial Roar",
        "power": 1.8,
        "mp_cost": 12,
        "type": "magical",
        "desc_key": "magic",
    },
    # Clockwork / Steam Skills
    "steam_vent": {
        "key_id": "steam_vent",
        "name": "Steam Vent",
        "power": 1.5,
        "mp_cost": 8,
        "type": "magical",
        "desc_key": "magic",
    },
    # Water / Aquatic Skills
    "water_jet": {
        "key_id": "water_jet",
        "name": "Water Jet",
        "power": 1.4,
        "mp_cost": 6,
        "type": "magical",
        "desc_key": "magic",
    },
    "tidal_wave": {
        "key_id": "tidal_wave",
        "name": "Tidal Wave",
        "power": 1.7,
        "mp_cost": 10,
        "type": "magical",
        "desc_key": "magic",
    },
    "bubble_beam": {
        "key_id": "bubble_beam",
        "name": "Bubble Beam",
        "power": 1.2,
        "mp_cost": 5,
        "type": "magical",
        "desc_key": "magic",
    },
    "crushing_depths": {
        "key_id": "crushing_depths",
        "name": "Crushing Depths",
        "power": 1.8,
        "mp_cost": 12,
        "type": "physical",
        "desc_key": "special_hit",
    },
    # Healing
    "mend": {
        "key_id": "mend",
        "name": "Mend",
        "heal_power": 30,  # Flat heal, can be scaled in DamageFormula if needed
        "mp_cost": 8,
        "type": "heal",
        "desc_key": "heal",
    },
    "regenerate": {
        "key_id": "regenerate",
        "name": "Regenerate",
        "heal_power": 60,
        "mp_cost": 15,
        "type": "heal",
        "desc_key": "heal",
    },
    # Void / Entropy Skills (Rank S)
    "void_slash": {
        "key_id": "void_slash",
        "name": "Void Slash",
        "power": 1.6,
        "mp_cost": 8,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "entropy_wave": {
        "key_id": "entropy_wave",
        "name": "Entropy Wave",
        "power": 2.0,
        "mp_cost": 15,
        "type": "magical",
        "desc_key": "magic",
    },
    "annihilate": {
        "key_id": "annihilate",
        "name": "Annihilate",
        "power": 2.5,
        "mp_cost": 25,
        "type": "magical",
        "desc_key": "magic",
    },
    # Wind / Storm Skills
    "gust": {
        "key_id": "gust",
        "name": "Gust",
        "power": 1.3,
        "mp_cost": 5,
        "type": "magical",
        "desc_key": "magic",
    },
    "aerial_dive": {
        "key_id": "aerial_dive",
        "name": "Aerial Dive",
        "power": 1.6,
        "mp_cost": 8,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "thunder_call": {
        "key_id": "thunder_call",
        "name": "Thunder Call",
        "power": 1.9,
        "mp_cost": 12,
        "type": "magical",
        "desc_key": "magic",
    },
    # Celestial Skills
    "arcane_pulse": {
        "key_id": "arcane_pulse",
        "name": "Arcane Pulse",
        "power": 1.5,
        "mp_cost": 8,
        "type": "magical",
        "desc_key": "magic",
    },
    "gravity_crush": {
        "key_id": "gravity_crush",
        "name": "Gravity Crush",
        "power": 1.7,
        "mp_cost": 10,
        "type": "physical",
        "desc_key": "special_hit",
    },
    "celestial_beam": {
        "key_id": "celestial_beam",
        "name": "Celestial Beam",
        "power": 1.9,
        "mp_cost": 12,
        "type": "magical",
        "desc_key": "magic",
    },
}
