name: Auto Update Branch

on:
  push:
    branches:
      - main
  # Allow manual trigger
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-update PRs that are behind
        uses: chinthakagodawita/autoupdate@v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          exclude: 'dependabot/*' 
          pr_filter: 'auto_merge'
